In [1]:
import pandas as pd
import numpy as np

In [2]:
js=pd.read_csv("js_table.csv")

In [3]:
lc=js['dwarf'].str.lower().tolist()
dw = [sub + '_js' for sub in lc]

In [4]:
js['Mv_error'] = list(zip(js['dM_V+'], js['dM_V-'].astype(float)))
js['r1_2_error'] = list(zip(js['dr_1/2+'], js['dr_1/2-'].astype(float)))
js['dist_error'] = list(zip(js['ddist+'], js['ddist-'].astype(float)))
js['Vhel_error'] = list(zip(js['dVhel+'], js['dVhel-'].astype(float)))
js['sigma_error'] = list(zip(js['dsig+'], js['dsig-'].astype(float)))
js['Fe_H_error'] = list(zip(js['d[Fe/H]+'], js['d[Fe/H]-'].astype(float)))
js['sigFe_H_error'] = list(zip(js['dsigFe/H+'], js['dsigFe/H-'].astype(float)))

In [5]:
imp=js.drop(columns=['dM_V+', 'dM_V-','dr_1/2+', 'dr_1/2-','ddist+','ddist-','dVhel+','dVhel-','dsig+','dsig-','d[Fe/H]+','d[Fe/H]-','dsigFe/H+','dsigFe/H-'])

In [6]:
imp

,dwarf,Mv,Mv_error,r1_2,r1_2_error,dist,dist_error,Vhel,Vhel_error,sigma,sigma_error,Fe_H,Fe_H_error,sigFe_H,sigFe_H_error
0,Tucana4,-3.50,"(0.28, -0.28)",127,"(26, -22.0)",48.0,"(4.0, -4.0)",0.0,"(0.0, nan)",NaN,"(nan, nan)",NaN,"(nan, nan)",NaN,"(nan, nan)"
1,Sculptor,-10.82,"(0.14, -0.14)",279,"(16, -16.0)",86.0,"(5.0, -5.0)",111.4,"(0.1, -0.1)",9.2,"(1.1, -1.1)",-1.73,"(0.03, -0.02)",0.44,"(0.02, -0.02)"
2,Cetus2,0.00,"(0.68, -0.68)",17,"(9, -5.0)",30.0,"(3.0, -3.0)",0.0,"(0.0, nan)",NaN,"(nan, nan)",NaN,"(nan, nan)",NaN,"(nan, nan)"
3,Cetus3,-2.45,"(0.57, -0.56)",90,"(32, -14.0)",251.0,"(24.0, -11.0)",0.0,"(0.0, nan)",NaN,"(nan, nan)",NaN,"(nan, nan)",NaN,"(nan, nan)"
4,Triangulum2,-1.60,"(0.76, -0.76)",16,"(4, -4.0)",28.4,"(1.6, -1.6)",-381.7,"(1.1, -1.1)",3.4,"(-9.9, -9.9)",-2.24,"(0.05, -0.05)",0.53,"(0.12, -0.38)"
5,Segue2,-1.98,"(0.88, -0.88)",40,"(4, -4.0)",37.0,"(3.0, -3.0)",-40.2,"(0.9, -0.9)",2.2,"(-9.9, -9.9)",-2.14,"(0.16, -0.15)",0.39,"(0.12, -0.13)"
6,DESJ0225+0304,-1.10,"(0.5, -0.3)",19,"(9, -5.0)",23.8,"(0.7, -0.5)",0.0,"(0.0, nan)",NaN,"(nan, nan)",NaN,"(nan, nan)",NaN,"(nan, nan)"
7,Hydrus1,-4.71,"(0.08, -0.08)",53,"(4, -4.0)",27.6,"(0.5, -0.5)",80.4,"(0.6, -0.6)",2.7,"(0.5, -0.4)",-2.52,"(0.09, -0.09)",0.41,"(0.08, -0.08)"
8,Fornax,-13.34,"(0.14, -0.14)",792,"(18, -18.0)",139.0,"(3.0, -3.0)",55.2,"(0.1, -0.1)",11.7,"(0.9, -0.9)",-1.07,"(0.02, -0.01)",0.27,"(0.01, -0.01)"
9,Horologium1,-3.76,"(0.56, -0.56)",40,"(1, -9.0)",87.0,"(13.0, -11.0)",112.8,"(2.5, -2.6)",4.9,"(2.8, -0.9)",-2.76,"(0.1, -0.1)",0.17,"(0.2, -0.03)"
10,Horologium2,-1.56,"(1.02, -1.02)",44,"(15, -14.0)",78.0,"(8.0, -7.0)",0.0,"(0.0, nan)",NaN,"(nan, nan)",NaN,"(nan, nan)",NaN,"(nan, nan)"
11,Reticulum2,-3.88,"(0.38, -0.38)",51,"(3, -3.0)",31.6,"(1.5, -1.4)",62.8,"(0.5, -0.5)",3.3,"(0.7, -0.7)",-2.65,"(0.07, -0.07)",0.28,"(0.09, -0.09)"
12,Eridanus2,-7.10,"(0.3, -0.3)",246,"(17, -17.0)",366.0,"(17.0, -17.0)",75.6,"(1.3, -1.3)",6.9,"(1.2, -0.9)",-2.38,"(0.13, -0.13)",0.47,"(0.12, -0.09)"
13,Reticulum3,-3.30,"(0.29, -0.29)",64,"(26, -23.0)",92.0,"(13.0, -13.0)",0.0,"(0.0, nan)",NaN,"(nan, nan)",NaN,"(nan, nan)",NaN,"(nan, nan)"
14,Pictor1,-3.67,"(0.6, -0.6)",32,"(15, -15.0)",126.0,"(19.0, -16.0)",0.0,"(0.0, nan)",NaN,"(nan, nan)",NaN,"(nan, nan)",NaN,"(nan, nan)"
15,Columba1,-4.20,"(0.2, -0.2)",117,"(12, -12.0)",183.0,"(10.0, -10.0)",0.0,"(0.0, nan)",NaN,"(nan, nan)",NaN,"(nan, nan)",NaN,"(nan, nan)"
16,Carina,-9.45,"(0.05, -0.05)",311,"(15, -15.0)",106.0,"(5.0, -5.0)",222.9,"(0.1, -0.1)",6.6,"(1.2, -1.2)",-1.80,"(0.02, -0.02)",0.24,"(9.99, nan)"
17,Pictor2,-3.20,"(0.4, -0.5)",47,"(20, -13.0)",45.0,"(5.0, -4.0)",0.0,"(0.0, nan)",NaN,"(nan, nan)",NaN,"(nan, nan)",NaN,"(nan, nan)"
18,Carina2,-4.50,"(0.1, -0.1)",92,"(8, -8.0)",36.2,"(0.6, -0.6)",477.2,"(1.2, -1.2)",3.4,"(1.2, -0.8)",-2.44,"(0.09, -0.09)",0.22,"(0.1, -0.07)"
19,Carina3,-2.40,"(0.2, -0.2)",30,"(8, -8.0)",27.8,"(0.6, -0.6)",284.6,"(3.4, -3.1)",5.6,"(4.3, -2.1)",0.00,"(nan, nan)",NaN,"(nan, nan)"
20,UMa2,-4.43,"(0.26, -0.26)",139,"(9, -9.0)",34.7,"(2.0, -1.9)",-116.5,"(1.9, -1.9)",5.6,"(1.4, -1.4)",-2.23,"(0.21, -0.24)",0.67,"(0.2, -0.15)"
21,Leo_T,-8.00,"(9.99, nan)",118,"(11, -11.0)",409.0,"(29.0, -27.0)",38.1,"(2.0, -2.0)",7.5,"(1.6, -1.6)",-1.91,"(0.12, -0.14)",0.43,"(0.13, -0.09)"
22,Segue1,-1.30,"(0.73, -0.73)",24,"(4, -4.0)",23.0,"(2.0, -2.0)",208.5,"(0.9, -0.9)",3.7,"(1.4, -1.1)",-2.71,"(0.45, -0.39)",0.95,"(0.42, -0.26)"
23,Leo1,-11.78,"(0.28, -0.28)",270,"(17, -16.0)",254.0,"(16.0, -15.0)",282.9,"(0.5, -0.5)",9.2,"(0.4, -0.4)",-1.48,"(0.02, -0.01)",0.26,"(0.01, -0.01)"
24,Sextans,-8.94,"(0.06, -0.06)",456,"(15, -15.0)",95.0,"(3.0, -3.0)",224.3,"(0.1, -0.1)",7.9,"(1.3, -1.3)",-1.97,"(0.04, -0.04)",0.38,"(0.03, -0.03)"
25,UMa1,-5.13,"(0.38, -0.38)",295,"(28, -28.0)",97.3,"(6.0, -5.7)",-55.3,"(1.4, -1.4)",7.0,"(1.0, -1.0)",-2.16,"(0.11, -0.13)",0.62,"(0.1, -0.08)"
26,Willman1,-2.90,"(0.74, -0.74)",33,"(8, -8.0)",45.0,"(10.0, -10.0)",-14.1,"(1.0, -1.0)",4.0,"(0.8, -0.8)",-2.19,"(0.08, -0.08)",0.00,"(nan, nan)"
27,Leo2,-9.74,"(0.04, -0.04)",171,"(10, -10.0)",233.0,"(14.0, -14.0)",78.3,"(0.6, -0.6)",7.4,"(0.4, -0.4)",-1.68,"(0.02, -0.03)",0.34,"(0.02, -0.02)"
28,Leo5,-4.29,"(0.36, -0.36)",49,"(16, -16.0)",169.0,"(4.0, -4.0)",170.9,"(2.1, -1.9)",2.3,"(3.2, -1.6)",-2.48,"(0.21, -0.21)",0.47,"(0.23, -0.13)"
29,Leo4,-4.99,"(0.26, -0.26)",114,"(13, -13.0)",154.0,"(5.0, -5.0)",132.3,"(1.4, -1.4)",3.3,"(1.7, -1.7)",-2.29,"(0.19, -0.22)",0.56,"(0.19, -0.14)"
30,Crater2,-8.20,"(0.1, -0.1)",1066,"(86, -86.0)",117.5,"(1.1, -1.1)",87.5,"(0.4, -0.4)",2.7,"(0.3, -0.3)",-1.98,"(0.1, -0.1)",0.22,"(0.04, -0.03)"
31,Virgo1,-0.80,"(0.9, -0.9)",38,"(12, -11.0)",87.0,"(13.0, -8.0)",0.0,"(0.0, nan)",NaN,"(nan, nan)",NaN,"(nan, nan)",NaN,"(nan, nan)"
32,Hydra2,-4.86,"(0.37, -0.37)",67,"(13, -13.0)",151.0,"(8.0, -7.0)",303.1,"(1.4, -1.4)",3.6,"(-9.9, -9.9)",-2.02,"(0.08, -0.08)",0.40,"(0.48, -0.26)"
33,Coma_Berenices,-4.28,"(0.25, -0.25)",69,"(5, -4.0)",42.0,"(1.6, -1.5)",98.1,"(0.9, -0.9)",4.6,"(0.8, -0.8)",-2.43,"(0.11, -0.11)",0.46,"(0.09, -0.08)"
34,Canes_Venatici2,-5.17,"(0.32, -0.32)",71,"(11, -11.0)",160.0,"(4.0, -4.0)",-128.9,"(1.2, -1.2)",4.6,"(1.0, -1.0)",-2.35,"(0.16, -0.19)",0.57,"(0.15, -0.12)"
35,Canes_Venatici1,-8.73,"(0.06, -0.06)",437,"(18, -18.0)",211.0,"(6.0, -6.0)",30.9,"(0.6, -0.6)",7.6,"(0.4, -0.4)",-1.91,"(0.04, -0.04)",0.39,"(0.03, -0.02)"
36,Bootes2,-2.94,"(0.74, -0.75)",39,"(5, -5.0)",42.0,"(1.0, -1.0)",-117.0,"(5.2, -5.2)",10.5,"(7.4, -7.4)",-2.79,"(0.06, -0.1)",0.35,"(-9.9, -9.9)"
37,Bootes1,-6.02,"(0.25, -0.25)",191,"(8, -8.0)",66.0,"(2.0, -2.0)",101.8,"(0.7, -0.7)",4.6,"(0.8, -0.6)",-2.35,"(0.09, -0.08)",0.44,"(0.07, -0.06)"
38,UMi,-9.03,"(0.05, -0.05)",405,"(21, -21.0)",76.0,"(4.0, -4.0)",-247.2,"(0.8, -0.8)",9.5,"(1.2, -1.2)",-2.12,"(0.03, -0.02)",0.33,"(0.02, -0.03)"
39,Draco2,-0.80,"(0.4, -1.0)",19,"(4, -3.0)",21.5,"(0.4, -0.4)",-342.5,"(1.1, -1.2)",5.9,"(-9.9, -9.9)",-2.70,"(0.1, -0.1)",0.24,"(-9.9, -9.9)"
40,Hercules,-5.83,"(0.17, -0.17)",216,"(20, -20.0)",132.0,"(6.0, -6.0)",45.0,"(1.1, -1.1)",5.1,"(0.9, -0.9)",-2.47,"(0.13, -0.12)",0.47,"(0.11, -0.08)"
41,Draco,-8.88,"(0.05, -0.05)",231,"(17, -17.0)",82.0,"(6.0, -6.0)",-290.7,"(0.7, -0.8)",9.1,"(1.2, -1.2)",-2.00,"(0.02, -0.02)",0.34,"(0.02, -0.02)"
42,Sagittarius,-13.50,"(0.15, -0.15)",2662,"(193, -193.0)",26.7,"(1.3, -1.3)",139.4,"(0.6, -0.6)",9.6,"(0.4, -0.4)",-0.53,"(0.03, -0.02)",0.17,"(0.02, -0.02)"
43,Sagittarius2,-5.20,"(0.1, -0.1)",33,"(2, -2.0)",70.1,"(2.3, -2.3)",0.0,"(0.0, nan)",NaN,"(nan, nan)",NaN,"(nan, nan)",NaN,"(nan, nan)"
44,Indus2,-4.30,"(0.19, -0.19)",181,"(70, -64.0)",214.0,"(16.0, -16.0)",0.0,"(0.0, nan)",NaN,"(nan, nan)",NaN,"(nan, nan)",NaN,"(nan, nan)"
45,Grus2,-3.90,"(0.22, -0.22)",93,"(16, -12.0)",53.0,"(5.0, -5.0)",0.0,"(0.0, nan)",NaN,"(nan, nan)",NaN,"(nan, nan)",NaN,"(nan, nan)"
46,Pegasus3,-4.10,"(0.5, -0.5)",78,"(31, -25.0)",205.0,"(20.0, -20.0)",-222.9,"(2.6, -2.6)",5.4,"(3.0, -2.5)",-2.40,"(0.15, -0.15)",0.00,"(nan, nan)"
47,Aquarius2,-4.36,"(0.14, -0.14)",160,"(26, -26.0)",107.9,"(3.3, -3.3)",-71.1,"(2.5, -2.5)",5.4,"(3.4, -0.9)",-2.30,"(0.5, -0.5)",0.00,"(nan, nan)"
48,Tucana2,-3.90,"(0.2, -0.2)",121,"(35, -35.0)",58.0,"(8.0, -8.0)",-129.1,"(3.5, -3.5)",8.6,"(4.4, -2.7)",-2.90,"(0.15, -0.16)",0.29,"(0.15, -0.12)"
49,Grus1,-3.47,"(0.59, -0.59)",28,"(23, -23.0)",120.0,"(12.0, -11.0)",-140.5,"(2.4, -1.6)",2.9,"(2.1, -1.0)",-1.42,"(0.55, -0.42)",0.41,"(0.49, -0.23)"
50,Pisces2,-4.23,"(0.38, -0.38)",60,"(1, -1.0)",183.0,"(15.0, -15.0)",-226.5,"(2.7, -2.7)",5.4,"(3.6, -2.4)",-2.45,"(0.07, -0.07)",0.48,"(0.7, -0.29)"
51,Tucana5,-1.60,"(0.49, -0.49)",16,"(5, -5.0)",55.0,"(9.0, -9.0)",0.0,"(0.0, nan)",NaN,"(nan, nan)",NaN,"(nan, nan)",NaN,"(nan, nan)"
52,Phoenix2,-2.70,"(0.4, -0.4)",37,"(8, -8.0)",84.3,"(4.0, -4.0)",0.0,"(0.0, nan)",NaN,"(nan, nan)",NaN,"(nan, nan)",NaN,"(nan, nan)"
53,Tucana3,-1.49,"(0.2, -0.2)",37,"(9, -9.0)",25.0,"(2.0, -2.0)",-102.3,"(0.4, -0.4)",1.2,"(-9.9, -9.9)",-2.42,"(0.07, -0.08)",0.19,"(-9.9, -9.9)"

In [7]:
imp.keys()

Index(['dwarf', 'Mv', 'Mv_error', 'r1_2', 'r1_2_error', 'dist', 'dist_error',
       'Vhel', 'Vhel_error', 'sigma', 'sigma_error', 'Fe_H', 'Fe_H_error',
       'sigFe_H', 'sigFe_H_error'],
      dtype='object')

In [8]:
columns=imp.iloc[:,np.r_[1:15]].keys().tolist()

In [9]:
columns

['Mv',
 'Mv_error',
 'r1_2',
 'r1_2_error',
 'dist',
 'dist_error',
 'Vhel',
 'Vhel_error',
 'sigma',
 'sigma_error',
 'Fe_H',
 'Fe_H_error',
 'sigFe_H',
 'sigFe_H_error']

In [10]:
import sat_array
from importlib import reload
reload(sat_array)

In [11]:
d = np.zeros(1, dtype=sat_array.mydtype).view(np.recarray)

In [14]:
#Mv
for i in range(len(dw)):
    d[dw[i]][columns[0]]=imp[imp['dwarf']==imp['dwarf'][i]].Mv
    d[dw[i]][columns[1]]=imp[imp['dwarf']==imp['dwarf'][i]].Mv_error
    
#r_1/2    
for i in range(len(dw)):
    d[dw[i]][columns[2]]=imp[imp['dwarf']==imp['dwarf'][i]].r1_2
    d[dw[i]][columns[3]]=imp[imp['dwarf']==imp['dwarf'][i]].r1_2_error
    
#distance    
for i in range(len(dw)):
    d[dw[i]][columns[4]]=imp[imp['dwarf']==imp['dwarf'][i]].dist
    d[dw[i]][columns[5]]=imp[imp['dwarf']==imp['dwarf'][i]].dist_error
    
#Vhel
for i in range(len(dw)):
    d[dw[i]][columns[6]]=imp[imp['dwarf']==imp['dwarf'][i]].Vhel
    d[dw[i]][columns[7]]=imp[imp['dwarf']==imp['dwarf'][i]].Vhel_error
    
#sigma
for i in range(len(dw)):
    d[dw[i]][columns[8]]=imp[imp['dwarf']==imp['dwarf'][i]].sigma
    d[dw[i]][columns[9]]=imp[imp['dwarf']==imp['dwarf'][i]].sigma_error
    
#Fe_H    
for i in range(len(dw)):
    d[dw[i]][columns[10]]=imp[imp['dwarf']==imp['dwarf'][i]].Fe_H
    d[dw[i]][columns[11]]=imp[imp['dwarf']==imp['dwarf'][i]].Fe_H_error
    
#sigFe_H
for i in range(len(dw)):
    d[dw[i]][columns[12]]=imp[imp['dwarf']==imp['dwarf'][i]].sigFe_H
    d[dw[i]][columns[13]]=imp[imp['dwarf']==imp['dwarf'][i]].sigFe_H_error

In [15]:
d[0].draco_js.Mv

array([-8.88])